version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: vue-json-pretty
    versions:
    - 2.0.2
  - dependency-name: fsevents
    versions:
    - 2.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: rippled-ws-client
    versions:
    - 1.6.3
